[package]
name = "iot_router_service"
version = "0.2.0"
edition = "2024"

[dependencies]
# Async Runtime
tokio = { version = "1.48", features = ["rt-multi-thread", "macros"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# gRPC
tonic = { version = "0.12", features = ["tls", "tls-roots", "transport", "gzip"] }
prost = "0.13"
tokio-stream = "0.1.17"
dotenv = "0.15.0"


[build-dependencies]
tonic-build = "0.12"


[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
